# Generated by Django 4.1.2 on 2022-10-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'verbose_name_plural': 'Listing2'},
        ),
    ]
