# Generated by Django 4.1.2 on 2022-10-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listings_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={},
        ),
    ]
